name:                philipphagenlocher
version:             0.1.0.0
github:              "bytewood/philipphagenlocher"
license:             BSD3
author:              "Peter Wood"
maintainer:          "peter.wood.za@gmail.com"
copyright:           "© bytewood 2021"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            default

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bytewood/philipphagenlocher#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  philipphagenlocher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - philipphagenlocher

tests:
  philipphagenlocher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - philipphagenlocher
